# Ce fichier est optimisé pour la production.
# Il ne "build" rien, il utilise les images déjà construites par la CI.
# Il charge automatiquement les variables depuis un fichier .env situé dans le même répertoire.

services:
  # Service de base de données PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: neoorga-db
    restart: always
    environment:
      # Ces variables sont lues depuis le fichier .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # Le port n'est pas exposé sur l'hôte, la communication se fait via le réseau Docker interne.
    # Healthcheck pour s'assurer que Postgres est prêt avant que d'autres services ne démarrent
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Service Backend (API Python/Flask)
  backend:
    # On utilise l'image dont le nom est construit à partir de la variable du .env
    image: ghcr.io/${GITHUB_REPO}/backend:latest
    container_name: neoorga-backend
    restart: always
    # Utilisation de la forme longue pour attendre que le healthcheck de la DB soit "healthy"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # L'URL de la base de données est construite à partir des variables du .env
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

  # Reverse Proxy Nginx (qui sert le frontend et proxy le backend)
  nginx:
    image: ghcr.io/${GITHUB_REPO}/nginx:latest
    container_name: neoorga-nginx
    restart: always
    depends_on:
      - backend
    networks:
      - default
      - proxy-net

volumes:
  postgres-data:

networks:
  proxy-net:
    external: true
